[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "flask-cors>=6.0.2",
    "flask-sqlalchemy>=3.1.1",
    "pytest>=9.0.2",
    "youtube-transcript-api>=1.2.4",
    "yt-dlp>=2026.2.21",
]
